export const addressValidationErrors = {
  INVALID_ADDRESS_ID: "Invalid Address Id",
  INVALID_FLAT_HOUSE_NO: "Invalid Flat House No",
  INVALID_AREA_COLONY_STREET: "Invalid Area Colony street",
  INVALID_ADDRESS: "Invalid Address",
  INVALID_COUNTRY: "Invalid Country",
  INVALID_CITY: "Invalid City",
  INVALID_STATE: "Invalid State",
  INVALID_MOBILE_NO: "Invalid Mobile No",
  INVALID_USER_ID: "Invalid User Id",
  INVALID_IS_DEFAULT: "Invalid Is Default",
  INVALID_PINCODE: "Invalid Pincode",
  INVALID_LATITUDE: "Invalid Latitude",
  INVALID_LONGITUDE: "Invalid Longitude",
  INVALID_ADDRESS_TYPE: "Invalid Address Type",
  INVALID_ADDRESS_TYPE_ID: "Invalid Address Type Id",
  INVALID_ADDRESS_TYPE_NAME: "Invalid Address Type Name",
  INVALID_BUSSINESS_ID: "Invalid Bussiness Id",
  INVALID_COORDINATES: "Invalid Coordinates",
};

export const orderValidationErrors = {
  INVALID_ORDER_ID: "Invalid Order Id",
  INVALID_ORDER_STATUS: "Invalid Order Status",
  INVALID_ORDER_TYPE: "Invalid Order Type",
  INVALID_TOTAL_AMOUNT: "Invalid Total Amount",
  INVALID_PAYMENT_MODE: "Invalid Payment Mode",
  INVALID_QUANTITY: "Invalid Quantity",
  INVALID_PRODUCT_ID: "Invalid Product Id",
  INVALID_ADDRESS_ID: "Invalid Address Id",
  INVALID_DISCOUNT_PRICE: "Invalid Discount Price",
  PRODUCT_ID_NOT_FOUND: "Product Id Not Found",
  ADDRESS_ID_NOT_FOUND: "Address Id Not Found",
  ORDER_ID_NOT_FOUND: "Order Id Not Found",
  MERCHANT_TRANSACTION_ID_NOT_FOUND: "Merchant Transaction Id Not Found",
  INVALID_MERCHANT_TRANSACTION_ID: " Invalid Merchant Transaction Id",
};
